# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='created_at',
        ),
    ]
