# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20170218_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='no_visa_requirement_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='visa_find_nearest_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='visa_header',
            field=models.CharField(default='Visa Requirements', max_length=255, verbose_name='Visa Header'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='visa_main_text',
            field=models.TextField(default='', verbose_name='Visa Main Text'),
        ),
    ]
