# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170218_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField(max_length=255, verbose_name='Step number')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Visa Step',
                'verbose_name_plural': 'Visa Steps',
            },
        ),
        migrations.CreateModel(
            name='VisaStepsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('important', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('visa_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.VisaSteps')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Visa Step Block',
                'verbose_name_plural': 'Visa Step Block',
            },
        ),
    ]
