# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_visasteps_visastepsblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visasteps',
            name='step_num',
            field=models.IntegerField(verbose_name='Step number'),
        ),
    ]
