# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20170217_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='accompanying',
            field=models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default=django.utils.datetime_safe.date.today, help_text='Select an item\u2026', max_length=255, verbose_name='Will you be accompanying by a person?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='get_review',
            field=models.CharField(blank=True, choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], help_text='Select an item\u2026', max_length=255, verbose_name='Would you like to review the Conference papers?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='section_1',
            field=models.CharField(choices=[('', ''), (b'1', b'Global challenges for innovation in management and business'), (b'2', b'Quantitative methods in management, economy and finance'), (b'3', b'National and regional innovation systems in BRICS and recently emerging economies'), (b'4', b'University-industry links and innovation in BRICS countries'), (b'5', b'Entrepreneurship and its development in BRICS, emerging markets and developed economies'), (b'6', b'Innovation in services, knowledge intensive services and creative industries'), (b'7', b'Modern technologies in logistics and services'), (b'8', b'Open Innovation in both large and small firms: cases of BRICS'), (b'9', b'Social innovation and innovation in social enterprises and other not-for- profit organizations'), (b'10', b'The impact of globalization on management research'), (b'11', b'Digital, IT-enabled and financial innovation: shaping the future'), (b'12', b'Cross Cultural Research - International issues in gender and management')], help_text='Sections your report corresponds to (by priority of compliance)', max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='section_2',
            field=models.CharField(blank=True, choices=[('', ''), (b'1', b'Global challenges for innovation in management and business'), (b'2', b'Quantitative methods in management, economy and finance'), (b'3', b'National and regional innovation systems in BRICS and recently emerging economies'), (b'4', b'University-industry links and innovation in BRICS countries'), (b'5', b'Entrepreneurship and its development in BRICS, emerging markets and developed economies'), (b'6', b'Innovation in services, knowledge intensive services and creative industries'), (b'7', b'Modern technologies in logistics and services'), (b'8', b'Open Innovation in both large and small firms: cases of BRICS'), (b'9', b'Social innovation and innovation in social enterprises and other not-for- profit organizations'), (b'10', b'The impact of globalization on management research'), (b'11', b'Digital, IT-enabled and financial innovation: shaping the future'), (b'12', b'Cross Cultural Research - International issues in gender and management')], help_text='Sections your report corresponds to (by priority of compliance)', max_length=255),
        ),
    ]
