# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20170218_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visastepsblock',
            name='important',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visastepsblock',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visastepsblock',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
