# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20170217_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Main Menu',
                'verbose_name_plural': 'Main Menu',
            },
        ),
    ]
