# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20170218_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visastepsblock',
            name='visa_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_step_block', to='landing.VisaSteps'),
        ),
    ]
