# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:29
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_menu_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizers',
            name='committie',
        ),
        migrations.AddField(
            model_name='organizers',
            name='committee',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('org', 'Organising Committee'), ('prog', 'Programme Committee')], max_length=8),
        ),
    ]
