# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20170218_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visastepsblock',
            options={'ordering': ('pk',), 'verbose_name': 'Visa Step Block', 'verbose_name_plural': 'Visa Step Block'},
        ),
        migrations.RemoveField(
            model_name='visastepsblock',
            name='order',
        ),
    ]
