# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20170218_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='practical_header',
            field=models.CharField(default='BRICS Practical Information', max_length=255, verbose_name='Practical Info Header'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='practical_main_text',
            field=models.TextField(default='', verbose_name='Practical Info Main Text'),
        ),
    ]
