# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_menu_anchor'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'News List',
                'verbose_name_plural': 'News List',
            },
        ),
    ]
