# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import landing.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20170218_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Practical Info',
                'verbose_name_plural': 'Practical Info',
            },
        ),
        migrations.CreateModel(
            name='PracticalBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to=landing.helpers.RandomFileName('practical'))),
                ('practical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_block', to='landing.Practical')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Practical Info Block',
                'verbose_name_plural': 'Practical Info Block',
            },
        ),
    ]
