# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('order',), 'verbose_name': 'Main Menu', 'verbose_name_plural': 'Main Menu'},
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
