# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import landing.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_practical_practicalblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicalblock',
            name='photo',
            field=models.ImageField(blank=True, upload_to=landing.helpers.RandomFileName('practical')),
        ),
        migrations.AlterField(
            model_name='practicalblock',
            name='text',
            field=models.TextField(),
        ),
    ]
