# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20170218_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalblock',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
