# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import landing.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_practicalblock_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='background_image',
            field=models.ImageField(default='', upload_to=landing.helpers.RandomFileName('main'), verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
