# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:51
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20170222_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='submission_start',
            field=django_markdown.models.MarkdownField(default='', verbose_name='Submission above button text'),
        ),
    ]
