# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_auto_20170222_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalblock',
            name='link_placeholder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publications',
            name='description',
            field=django_markdown.models.MarkdownField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='visastepsblock',
            name='important',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='visastepsblock',
            name='text',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
    ]
