# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_auto_20170222_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='fees_header',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='fees_text',
            field=django_markdown.models.MarkdownField(blank=True, default=''),
        ),
    ]
