# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_auto_20170907_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='externalLink',
            field=models.BooleanField(default=False, verbose_name='External link'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='externalURL',
            field=models.URLField(blank=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='section_1',
            field=models.CharField(choices=[('', '')], help_text='Sections your report corresponds to (by priority of compliance)', max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='section_2',
            field=models.CharField(blank=True, choices=[('', '')], help_text='Sections your report corresponds to (by priority of compliance)', max_length=255),
        ),
    ]
