# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_auto_20170907_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='anchor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='section',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
